dist: bionic
sudo: require

language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test

before_install:
    - sudo apt-get update -y
    - sudo apt install gcc-10 g++-10
    - sudo apt-get install -y gcovr
    - pip install --user cpp-coveralls

script:
  - mkdir build && cd build && CXX=/usr/bin/g++-10 CC=/usr/bin/gcc-10 cmake -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release -DCOVERAGE=1 ..
  - ./build/tests/tests

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*tests.*" -E ".*CMakeFiles.*"