dist: bionic
sudo: require

language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test

before_install:
    - sudo apt-get update -y
    - sudo apt-get install -y gcovr
    - pip install --user cpp-coveralls

script:
  - mkdir build && cd build && cmake -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Release -DCOVERAGE=1 ..
  - cmake --build .
  - ./algo-tests

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*tests.*" -E ".*CMakeFiles.*"
