dist: bionic
sudo: require

language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      env:
         - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

before_install:
    - sudo apt-get update -y
    - sudo apt install gcc-10 g++-10
    - sudo apt-get install -y -qq lcov curl
    - eval "${MATRIX_EVAL}"


script:
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=abc12345
  - ./scripts/build.sh 20 Debug -Wall ON
  - ./scripts/run.sh
  - cd build && cmake --build . --target coveralls
