dist: bionic
sudo: require

language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      env:
         - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

before_install:
    - sudo apt-get update -y
    - sudo apt install gcc-8 g++-8 gcc-9 g++-9 gcc-10 g++-10
    - sudo apt-get install -y gcovr
    - pip install --user cpp-coveralls
    - eval "${MATRIX_EVAL}"


script:
  - ./scripts/build.sh Debug -Wall 1
  - ./scripts/run.sh

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*tst.*" -E ".*CMakeFiles.*"