name: build_action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.1.1

    - name: Install gcc and g++10
      run: |
           sudo apt update
           sudo apt install gcc-10 g++-10
      shell: bash

    - name: Compile and run tests (C++20 Release)
      run: ./scripts/build.sh 1 20 Release

    - name: Compile and run tests (C++20 Debug)
      run: ./scripts/build.sh 1 20

    - name: Compile and run tests (C++17 Release)
      run: ./scripts/build.sh 1 17 Release

    - name: Compile and run tests (C++17 Debug)
      run: ./scripts/build.sh 1 17
