name: build_action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.1.1

    - name: Install gcc and g++10
      run: |
           sudo apt update
           sudo apt install gcc-10 g++-10
      shell: bash

    - name: Compile and run tests (Release)
      run: ./scripts/build.sh Release
      
    - name: Compile and run tests (Debug)
      run: ./scripts/build.sh
